a=6;
b=2;

# THIS OPERATOR IS USED TO THE ADDITION OF TWO OPERAND
c=a+b;
print("ADDITION OF TWO OPERATER:-",c)


#THIS IS SUBTRACTON OPERATOR
q=a-b;
print("SUBTRATION OF TWO NUMBER:-",q)

# THIS IS MULTIPICATION OPERATOR
E=a*b;
print("MULTIPICATION OF TWO NUMBER:-",E)

# THIS IS DIVISION OPERATOR
I=a/b
print("DIVISION OF TWO NUMBER",I)

# THIS IS DIVISION(floor) OPERATOR
T=a//b
print("DIVISION OF TWO NUMBER",T)

#THIS IS MODULES OPERATER
M=a%b;
print("MODULES OF TWO NUMBER",M)

# THIS IS EXPONENTIATON OPERATER
E=a**b;
print("EXPOENTIAL OF TWO NUMBER",E)
